name: Laravel CI

on:
  push:
    branches:
      - main
      - dev
      - 'feature/**'
      - 'bugfix/**'

  pull_request:
      branches:
        - main
        - dev

jobs:
  # 🧪 FIRST JOB → Runs tests
  laravel-tests:
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: test_db
      DB_USERNAME: test_user
      DB_PASSWORD: secret

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring, pdo, pgsql

      - name: Copy .env
        run: cp apps/backend/.env.testing apps/backend/.env

      - name: Install dependencies
        working-directory: apps/backend
        run: composer install --no-progress --prefer-dist

      - name: Generate app key
        working-directory: apps/backend
        run: php artisan key:generate

      - name: Set correct permissions (optional but safe)
        working-directory: apps/backend
        run: chmod -R 777 storage bootstrap/cache

      - name: Run migrations
        working-directory: apps/backend
        run: php artisan migrate --force

      - name: Run tests
        working-directory: apps/backend
        run: php artisan test

  # 🐳 SECOND JOB → Build Docker
  docker-build:
    runs-on: ubuntu-latest

    # 👇 THIS IS KEY → runs only if tests pass
    needs: laravel-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f docker/php/Dockerfile -t kijani-app .